-- Week 4: Rating App
-- Run this in Supabase SQL Editor before deploying the Week 4 app changes.

begin;

-- Preserve the original seeded captions while making every new generation
-- attributable and reproducible.
alter table public.captions
  add column if not exists prompt text,
  add column if not exists author_id uuid references auth.users(id) on delete set null,
  add column if not exists generation_model text;

alter table public.captions enable row level security;

drop policy if exists "Authenticated users can create captions" on public.captions;
create policy "Authenticated users can create captions"
on public.captions
for insert
to authenticated
with check ((select auth.uid()) = author_id);

-- A user has one mutable vote per caption. Raw votes are private; the app gets
-- public community totals from the constrained aggregate function below.
create table if not exists public.caption_votes (
  id bigint generated by default as identity primary key,
  caption_id bigint not null references public.captions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  value smallint not null check (value in (-1, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (caption_id, user_id)
);

alter table public.caption_votes enable row level security;

drop policy if exists "Users can read their own caption votes" on public.caption_votes;
drop policy if exists "Users can create their own caption votes" on public.caption_votes;
drop policy if exists "Users can update their own caption votes" on public.caption_votes;
drop policy if exists "Users can delete their own caption votes" on public.caption_votes;

create policy "Users can read their own caption votes"
on public.caption_votes
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own caption votes"
on public.caption_votes
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own caption votes"
on public.caption_votes
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own caption votes"
on public.caption_votes
for delete
to authenticated
using ((select auth.uid()) = user_id);

-- The function returns totals only: it never reveals who voted or how a
-- particular person voted. The underlying vote rows stay protected by RLS.
create or replace function public.caption_vote_totals()
returns table (
  caption_id bigint,
  upvotes bigint,
  downvotes bigint,
  score bigint
)
language sql
security definer
set search_path = public
as $$
  select
    caption_id,
    count(*) filter (where value = 1)::bigint as upvotes,
    count(*) filter (where value = -1)::bigint as downvotes,
    coalesce(sum(value), 0)::bigint as score
  from public.caption_votes
  group by caption_id;
$$;

revoke all on function public.caption_vote_totals() from public;
grant execute on function public.caption_vote_totals() to anon, authenticated;

-- `images` is not currently written by the app, but it is still a public
-- schema table and needs RLS enabled. Public reads preserve future caption
-- image rendering while writes remain denied by default.
alter table public.images enable row level security;

drop policy if exists "Anyone can read images" on public.images;
create policy "Anyone can read images"
on public.images
for select
to anon, authenticated
using (true);

commit;
